### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by r00bal** [MalgorzataMarczynska/goit-react-hw-03-phonebook#1]
https://github.com/MalgorzataMarczynska/goit-react-hw-03-phonebook/blob/849a5822671b3dbc368b042fae7733fb654ba837/src/components/App.jsx#L61-L68

Dlaczego tutaj używasz try catch ? Czy spodziewasz sie błedu w samym setState?

**Comment by MalgorzataMarczynska** [comment]
Bardziej w samym procesie parsowania do JSON-a, a dopiero w konsekwencji do setState. Aplikacja ma teraz niewiele wpisów, ale większa ilość obiektów może już uprawdopodobnić jakieś błędy w tym momencie, uwzględniając jeszcze zapisy w local storage'u.
